# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ptmc <- function(model, settings, update_ind, PTMCpar) {
    .Call('_ptmc_run_ptmc', PACKAGE = 'ptmc', model, settings, update_ind, PTMCpar)
}

